export const qk = {
  units: ["units"],
  brands: ["brands"],
  taxes: ["taxes"],
  attributes: ["attributes"],
  attributeValues: (attrId) => ["attributeValues", attrId],
  categories: ["categories"],
  categoryAttributes: (categoryId) => ["categoryAttributes", categoryId],
  products: (filters) => ["products", filters],
  product: (id) => ["product", id],
  variants: (productId) => ["variants", productId],
  variantAttributes: (variantId) => ["variantAttributes", variantId],
  prices: (variantId) => ["prices", variantId],
  stock: ["stock"],
  stockMovements: ["stockMovements"],
  parties: (filters) => ["parties", filters],
  party: (id) => ["party", id],
  quotations: ["quotations"],
  quotationItems: (id) => ["quotationItems", id],
  invoices: ["invoices"],
  invoiceItems: (id) => ["invoiceItems", id],
  purchases: ["purchases"],
  payments: ["payments"],
  dashboard: ["dashboard"],
};